# Publish on NPM whenever a new version is found in `package.json`.
# All releases are `beta` tagged.

# https://github.com/marketplace/actions/npm-publish
name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: studio-v3-plugin-v1
          token: ${{ secrets.NPM_TOKEN }}
